#!/bin/bash
usage(){
  echo "Usage: ${0} n, where n > 0" 1>&2
  exit 1
}
if [ ${#} -ne 1 ]
then
  echo "Incorrect number of parameters" 1>&2
  usage
elif [ "${1}"-lt 1 ] 
then
  echo "${1} is not > 0" 1>&2
  usage
fi

i=$((${1}-1))
total=$1
while [ "${i}" -gt 1 ]; do 
   total=$((${total} * ${i}))
   i=$((${i}-1))
done
echo "${1} factorial is ${total}"
