#!/bin/bash
# Answers whether a candidate word might be a good password

usage () {
  echo "Usage: $0 password" >&2
  exit 1
}

if [ ${#} -ne 1 ]; then
  usage
fi

egrep "^$1$" /usr/share/dict/words > /dev/null

if [ $? -eq 0 ]; then
  echo Not a good password
else
  echo Maybe a good password
fi
